//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP_Group3_StockManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string ProductName { get; set; }
        public string SupplierName { get; set; }
        public int TotalQuantity { get; set; }
        public Nullable<int> ReleaseQuantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
