//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP_Group3_StockManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Inventories = new HashSet<Inventory>();
            this.Products = new HashSet<Product>();
        }
    
        public int SupplierID { get; set; }

        [Display(Name = "Supplier name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Supplier Name required")]
        public string SupplierName { get; set; }

        [Display(Name = "Supplier Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Supplier Address required")]
        public string SupplierAddress { get; set; }

        [Display(Name = "Supplier Contact")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Supplier Contact required")]
        public string SupplierContact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
